name: Globoplay

options:
  preGenCommand: ../scripts/secrets/gen_secrets.sh
  bundleIdPrefix: hilst
  deploymentTarget: 
    iOS: 17.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

targets:
  Globoplay:
    type: application
    platform: iOS
    sources: 
      - Sources
      - Resources
    settings:
      base:
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: 7QSV5W38SD # TROCAR PELO SEU DEVELOPMENT TEAM
        DEVELOPMENT_ASSET_PATHS: "\"Resources/Preview Content\""
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: Sources/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen_Generation: YES
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]

  GloboplayTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - Tests
    dependencies:
      - target: Globoplay
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        DEVELOPMENT_TEAM: 7QSV5W38SD # TROCAR PELO SEU DEVELOPMENT TEAM
    info:
      path: Tests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)

  GloboplayUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: 
      - UITests
    dependencies:
      - target: Globoplay
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        DEVELOPMENT_TEAM: 7QSV5W38SD # TROCAR PELO SEU DEVELOPMENT TEAM
    info:
      path: UITests/Info.plist
      properties:
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)